### ISSUE TITLE
Could the method remove TE in the inference stage?

### ISSUE THREAD

**Issue by Changes92** [wusize/ovdet#7]
Thanks for your great work!

I'm just wondering about the inference stage. The proposed method still requires the whole Text Encoder in the inference stage for each image, which is different from existing OVD works that only use text embedding. This leads to a significantly large model scale and unsatisfactory inference speed, even doubling the model parameters. Is it possible to remove the text encoder in the inference stage?

**Comment by wusize** [comment]
Hi, thanks for your question！Directly matching the pseudo words with real word embeddings yields poor performance. It might require extra losses to more strictly align the pseudo words  to real word embeddings. And the word numbers of category names vary, making the matching complicated. 
We modified the [forward function](https://github.com/wusize/ovdet/blob/main/ovdet/models/vlms/clip/text_encoder.py#L65) of Text Encoder so that the context length is not 77 but the number of pseudo words, which makes the inference time acceptable.

**Comment by wusize** [comment]
That's because the pseudo words are aligned to the input space of text encoder. In other OVD baselines such as VLDet, the visual embeddings are aligned to the output space of text encoder.
